# Generated by Django 4.0 on 2021-12-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_1', to='account.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_2', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=2048)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user')),
            ],
        ),
    ]
